// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.27.0

package storage

import (
	"time"

	uuid "github.com/gofrs/uuid"
)

type Comment struct {
	ID        uuid.UUID `json:"id"`
	Comment   string    `json:"comment"`
	AuthorID  uuid.UUID `json:"authorId"`
	PostID    uuid.UUID `json:"postId"`
	CreatedAt time.Time `json:"createdAt"`
}
