package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"dataloader/storage"
)

// Author is the resolver for the author field.
func (r *postResolver) Author(ctx context.Context, obj *storage.Post) (storage.Author, error) {
	return r.AuthorLoader.Load(ctx, obj.AuthorID)
}
