package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"dataloader/graph/gen"
	"dataloader/storage"
	"fmt"
	"time"
)

// Bio is the resolver for the bio field.
func (r *authorResolver) Bio(ctx context.Context, obj *storage.Author) (*string, error) {
	if obj.Bio.Valid {
		return &obj.Bio.String, nil
	}
	return nil, nil
}

// CreatedAt is the resolver for the createdAt field.
func (r *postResolver) CreatedAt(ctx context.Context, obj *storage.Post) (time.Time, error) {
	return obj.CreatedAt.Time, nil
}

// Author returns gen.AuthorResolver implementation.
func (r *Resolver) Author() gen.AuthorResolver { return &authorResolver{r} }

// Post returns gen.PostResolver implementation.
func (r *Resolver) Post() gen.PostResolver { return &postResolver{r} }

type authorResolver struct{ *Resolver }
type postResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *postResolver) Content(ctx context.Context, obj *storage.Post) (*string, error) {
	panic(fmt.Errorf("not implemented: Content - content"))
}
