package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	storage1 "multimodular/comment/storage"
	"multimodular/post/storage"

	"github.com/gofrs/uuid"
)

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id uuid.UUID) (bool, error) {
	return true, r.CommentQueries.DeleteComment(ctx, id)
}

// LeaveComment is the resolver for the leaveComment field.
func (r *mutationResolver) LeaveComment(ctx context.Context, request storage1.LeaveCommentParams) (storage1.Comment, error) {
	panic(fmt.Errorf("not implemented: LeaveComment - leaveComment"))
}

// Comments is the resolver for the comments field.
func (r *postResolver) Comments(ctx context.Context, obj *storage.Post, postID uuid.UUID) ([]storage1.Comment, error) {
	panic(fmt.Errorf("not implemented: Comments - comments"))
}
