package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	gen1 "multimodular/graph/gen"
	"time"
)

// Ping is the resolver for the ping field.
func (r *mutationResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Ping is the resolver for the ping field.
func (r *queryResolver) Ping(ctx context.Context) (string, error) {
	return "pong", nil
}

// Ping is the resolver for the ping field.
func (r *subscriptionResolver) Ping(ctx context.Context) (<-chan string, error) {
	result := make(chan string)

	defer close(result)
	go func() {
		for {
			select {
			case <-time.After(10 * time.Second):
				result <- "pong"
			case <-ctx.Done():
				break
			}
		}
	}()

	return result, nil
}

// Mutation returns gen1.MutationResolver implementation.
func (r *Resolver) Mutation() gen1.MutationResolver { return &mutationResolver{r} }

// Query returns gen1.QueryResolver implementation.
func (r *Resolver) Query() gen1.QueryResolver { return &queryResolver{r} }

// Subscription returns gen1.SubscriptionResolver implementation.
func (r *Resolver) Subscription() gen1.SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
