package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	"multimodular/post/storage"

	"github.com/gofrs/uuid"
)

// MakeDraft is the resolver for the makeDraft field.
func (r *mutationResolver) MakeDraft(ctx context.Context, request storage.MakeDraftParams) (storage.Post, error) {
	panic(fmt.Errorf("not implemented: MakeDraft - makeDraft"))
}

// Publish is the resolver for the publish field.
func (r *mutationResolver) Publish(ctx context.Context, id int) (storage.Post, error) {
	panic(fmt.Errorf("not implemented: Publish - publish"))
}

// Posts is the resolver for the posts field.
func (r *queryResolver) Posts(ctx context.Context, authorID uuid.UUID) (storage.Post, error) {
	panic(fmt.Errorf("not implemented: Posts - posts"))
}
