package resolver

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.49

import (
	"context"
	"fmt"
	gen1 "multimodular/graph/gen"
	storage2 "multimodular/post/storage"
	"time"

	"github.com/gofrs/uuid"
)

// PublishedAt is the resolver for the publishedAt field.
func (r *postResolver) PublishedAt(ctx context.Context, obj *storage2.Post) (*time.Time, error) {
	panic(fmt.Errorf("not implemented: PublishedAt - publishedAt"))
}

// Post returns gen1.PostResolver implementation.
func (r *Resolver) Post() gen1.PostResolver { return &postResolver{r} }

type postResolver struct{ *Resolver }

// !!! WARNING !!!
// The code below was going to be deleted when updating resolvers. It has been copied here so you have
// one last chance to move it out of harms way if you want. There are two reasons this happens:
//   - When renaming or deleting a resolver the old code will be put in here. You can safely delete
//     it when you're done.
//   - You have helper methods in this file. Move them out to keep these resolver files clean.
func (r *postResolver) CreatedAt(ctx context.Context, obj *storage2.Post) (time.Time, error) {
	panic(fmt.Errorf("not implemented: CreatedAt - createdAt"))
}
func (r *postResolver) AuthorID(ctx context.Context, obj *storage2.Post) (uuid.UUID, error) {
	panic(fmt.Errorf("not implemented: AuthorID - authorId"))
}
